#!/bin/sh
#========auto deploy config start========
#-----needful param--------
JAVA_HOME_CONFIG="/home/appops/autoDeploy/software/jdk-oracle-1.7.0_64/"
XMX_CONFIG="512"
XMS_CONFIG="512"
MAX_PERM_CONFIG="128"
TOMCAT7_USER_CONFIG="appops"

#-----extra param----------
TOMCAT7_GROUP_CONFIG="netease"
NETEASE_COOKIE_CONFIG="NTESqa_ompSI"
APPNAME_CONFIG="yipinTest_qa_omp_omp"
JMX_REMOTE_PORT_CONFIG=""
LANG_CONFIG="en_US.UTF-8"
JVM_EXTRA_CONFIG=""
XDEBUG_ADDRESS=""
#========auto deploy config end========

NETEASE_SPACE=/home/${TOMCAT7_USER_CONFIG}
NETEASE_SPACE_LIB=${NETEASE_SPACE}/lib/
NETEASE_COOKIE=${NETEASE_COOKIE_CONFIG}
TOMCAT7_USER=${TOMCAT7_USER_CONFIG}

if [ -z "$TOMCAT7_GROUP_CONFIG" ];then
    TOMCAT7_GROUP="netease"
else
    TOMCAT7_GROUP="$TOMCAT7_GROUP_CONFIG"
fi

# CATALINA_TMPDIR
CATALINA_TMPDIR=/tmp
export CATALINA_TMPDIR

# The home directory of the Java development kit (JDK). You need at least
# JDK version 1.5. If JAVA_HOME is not set, some common directories for 
# OpenJDK, the Sun JDK, and various J2SE 1.5 versions are tried.
JAVA_HOME="$JAVA_HOME_CONFIG"

if [ -z "$APPNAME_CONFIG" ];then
    APPNAME="Tomcat"
else
    APPNAME="$APPNAME_CONFIG"
fi

# You may pass JVM startup parameters to Java here. If unset, the default
# options will be: -Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC
#
# Use "-XX:+UseConcMarkSweepGC" to enable the CMS garbage collector (improved
# response time). If you use that option and you run Tomcat on a machine with
# exactly one CPU chip that contains one or two cores, you should also add
# the "-XX:+CMSIncrementalMode" option.
JAVA_OPTS="-Djava.awt.headless=true \
-server -Xms${XMS_CONFIG}m -Xmx${XMX_CONFIG}m -XX:MaxPermSize=${MAX_PERM_CONFIG}m \
-Dcom.netease.appname=${APPNAME} \
-verbose:gc -XX:+PrintGCDetails -Xloggc:${CATALINA_BASE}/logs/gc.log -XX:+PrintGCTimeStamps \
-Djava.library.path=${NETEASE_SPACE_LIB} \
-Dforeign.domain=true \
-Dorg.apache.catalina.SESSION_COOKIE_NAME=${NETEASE_COOKIE} \
-Dsun.rmi.transport.tcp.responseTimeout=20000 \
-Dsun.rmi.dgc.client.gcInterval=7200000 \
-Dsun.rmi.dgc.server.gcInterval=7200000 \
-Dcom.sun.management.jmxremote \
-Dcom.sun.management.jmxremote.ssl=false \
-Dcom.sun.management.jmxremote.authenticate=false \
-Dlog.dir=${CATALINA_BASE}/logs \
"

# Jmx port config
if [ ! -z "$JMX_REMOTE_PORT_CONFIG" ];then
	JAVA_OPTS="${JAVA_OPTS} -Dcom.sun.management.jmxremote.port=${JMX_REMOTE_PORT_CONFIG} " 
fi

# Runtime Lang
if [ -z "${LANG_CONFIG}" ];then
	export LANG="en_US.UTF-8"
else
	export LANG="${LANG_CONFIG}"
fi

#-javaagent:$NETEASE_SPACE_LIB/aspectjweaver.jar \
#-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8890,suspend=n \

if [ ! -z "${XDEBUG_ADDRESS}" ];then
    JAVA_OPTS="${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=127.0.0.1:${XDEBUG_ADDRESS},server=y,suspend=n"
fi

# JVM extra config(for compatible)
if [ ! -z "$JVM_EXTRA_CONFIG" ];then
    JAVA_OPTS="${JAVA_OPTS} ${JVM_EXTRA_CONFIG}"
fi

# nss-agent
web_app_root=$(fgrep docBase ${CATALINA_BASE}/conf/server.xml | awk -F '"' '{print $4}')
nss_java_agent_path=$web_app_root/WEB-INF/classes/sentry-javaagent-home/sentry-javaagent-premain-2.0.0.jar
nss_java_agent_lib=$web_app_root/WEB-INF/lib
if [ -f "$nss_java_agent_path" ]; then
   JAVA_OPTS="${JAVA_OPTS} -javaagent:$nss_java_agent_path"
   JAVA_OPTS="${JAVA_OPTS} -Dsentry_collector_libpath=$nss_java_agent_lib"
fi

# To enable remote debugging uncomment the following line.
# You will then be able to use a java debugger on port 8000.
#JAVA_OPTS="${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"

# Java compiler to use for translating JavaServer Pages (JSPs). You can use all
# compilers that are accepted by Ant's build.compiler property.
JSP_COMPILER=javac

# Use the Java security manager? (yes/no, default: no)
#TOMCAT7_SECURITY=no

# Number of days to keep logfiles in /var/log/tomcat7. Default is 14 days.
#LOGFILE_DAYS=14

# Location of the JVM temporary directory
# WARNING: This directory will be destroyed and recreated at every startup !
#JVM_TMP=/tmp/tomcat7-temp

# If you run Tomcat on port numbers that are all higher than 1023, then you
# do not need authbind.  It is used for binding Tomcat to lower port numbers.
# NOTE: authbind works only with IPv4.  Do not enable it when using IPv6.
# (yes/no, default: no)
#AUTHBIND=no

export LD_LIBRARY_PATH=$NETEASE_SPACE_LIB:$LD_LIBRARY_PATH

if [ -d $CATALINA_BASE/logs ];then
    find -L $CATALINA_BASE/logs -name "*.log*"  -mtime +30 -exec rm {} \;
fi
