name: depblog
version: 1
cron:
- description: find new blog to mail
  url: /api/blog/fetch
  schedule: every 4 hours
  timezone: Beijing
- description: find top blog to mail
  url: /api/mail/top
  schedule: every monday of month 10:00
  timezone: Beijing
- description: fetch blog view
  url: /api/blog/view
  schedule:  every day of month 03:00
  timezone: Beijing
